### ISSUE TITLE
Automate PyPI package build

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/py-thesaurus-interface#24]
Build and upload the PyPI package automatically upon releases.

**Comment by azaf** [comment]
As @akorosov said, I have my commit uploaded here. Since this issue is created beforehand, I assign my commit with his guidance to this issue.
Dear @aperrin66 or Dear @akorosov please make the "PYPI_TOKEN" variable configured in the configuration of travis based on the nansen acount information in order to pass the tests. I think this code is ready.

**Comment by azaf** [comment]
I closed the old pull request and make a new one. This one is the correct one.

**Comment by akorosov** [comment]
Good job @azaf ! Thank you!!!
